# Generated by Django 3.1.3 on 2020-12-06 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0007_auto_20201205_1206'),
        ('styles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('focus', models.ManyToManyField(to='styles.Style')),
                ('instructor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_instructor', to='people.martialartist')),
                ('students', models.ManyToManyField(to='people.MartialArtist')),
            ],
        ),
    ]
