# Generated by Django 3.1.3 on 2020-12-07 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trainingclass',
            options={'verbose_name': 'Class', 'verbose_name_plural': 'Classes'},
        ),
    ]
