# Generated by Django 3.1.3 on 2021-01-02 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0010_auto_20201216_1220'),
        ('teachings', '0002_auto_20201206_2053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingclass',
            name='instructor',
        ),
        migrations.AddField(
            model_name='trainingclass',
            name='instructors',
            field=models.ManyToManyField(related_name='class_instructors', to='people.MartialArtist'),
        ),
    ]
