# Generated by Django 6.0.1 on 2026-01-26 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachings', '0003_auto_20210102_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingclass',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
