# Generated by Django 3.1.3 on 2020-12-03 22:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('styles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RankType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordinal', models.PositiveIntegerField(default=0)),
                ('title', models.CharField(max_length=100)),
                ('indicator', models.CharField(blank=True, max_length=50, null=True)),
                ('time_in_grade', models.PositiveIntegerField(blank=True, null=True)),
                ('time_in_style', models.PositiveIntegerField(blank=True, null=True)),
                ('test_required', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('style', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='styles.style')),
            ],
            options={
                'ordering': ['ordinal'],
            },
        ),
    ]
