# Generated by Django 3.1.3 on 2020-11-28 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ranktypes',
            options={'ordering': ['ordinal']},
        ),
        migrations.AlterField(
            model_name='ranktypes',
            name='ordinal',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
