# Generated by Django 3.1.3 on 2020-12-05 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranks', '0002_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rank',
            name='test_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
