# Generated by Django 3.1.3 on 2020-11-28 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('styles', '0001_initial'),
        ('ranks', '0002_auto_20201128_0336'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RankTypes',
            new_name='RankType',
        ),
    ]
