# Generated by Django 3.1.3 on 2020-12-18 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_item_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='quantity_on_hand',
            field=models.SmallIntegerField(default=0),
        ),
    ]
