# Generated by Django 6.0.1 on 2026-01-26 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0011_alter_martialartist_id_alter_sponsor_id_and_more'),
        ('store', '0005_invoice_lineitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ['-date_ordered']},
        ),
        migrations.AlterField(
            model_name='invoice',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='item',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='lineitem',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['-date_ordered'], name='store_invoi_date_or_d56590_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['purchaser', '-date_ordered'], name='store_invoi_purchas_90b5f8_idx'),
        ),
    ]
