# Generated by Django 3.1.3 on 2020-12-03 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('styles', '0001_initial'),
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='martialartist',
            name='styles',
            field=models.ManyToManyField(to='styles.Style'),
        ),
    ]
