# Generated by Django 3.1.3 on 2020-11-26 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('middle_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('street', models.CharField(max_length=70)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=2)),
                ('zip', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=100)),
                ('birthday', models.DateField()),
                ('isFemale', models.BooleanField(default=False)),
                ('notes', models.TextField()),
                ('isParent', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
