# Generated by Django 3.1.3 on 2020-12-05 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_auto_20201205_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='martialartist',
            name='sponsor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='people.sponsor'),
        ),
    ]
