# Generated by Django 3.1.3 on 2020-11-26 23:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_sponsor'),
    ]

    operations = [
        migrations.AddField(
            model_name='martialartist',
            name='sponsor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='people.sponsor'),
        ),
        migrations.AddField(
            model_name='martialartist',
            name='telephone',
            field=models.CharField(default='888-888-8888', max_length=15),
        ),
        migrations.AddField(
            model_name='sponsor',
            name='telephone',
            field=models.CharField(default='888-888-8888', max_length=15),
        ),
    ]
