# Generated by Django 3.1.3 on 2020-12-05 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0003_auto_20201205_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='martialartist',
            name='email',
            field=models.EmailField(blank=True, default='someone@nowhere.com', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='email',
            field=models.EmailField(blank=True, default='someone@nowhere.com', max_length=254, null=True),
        ),
    ]
