# Generated by Django 3.1.3 on 2020-11-28 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0004_auto_20201126_2358'),
    ]

    operations = [
        migrations.AddField(
            model_name='martialartist',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='people/images'),
        ),
        migrations.AddField(
            model_name='sponsor',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='people/images'),
        ),
    ]
