# Generated by Django 3.1.3 on 2020-12-05 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0005_auto_20201205_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='martialartist',
            name='enrollment_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
