# Generated by Django 3.1.3 on 2020-12-16 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tuition', '0001_initial'),
        ('people', '0008_martialartist_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='martialartist',
            options={'ordering': ['last_name', 'first_name']},
        ),
        migrations.AlterModelOptions(
            name='sponsor',
            options={'ordering': ['last_name', 'first_name']},
        ),
        migrations.AddField(
            model_name='martialartist',
            name='paymentPlan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tuition.paymentplan'),
        ),
    ]
