# Generated by Django 3.1.3 on 2020-12-16 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0009_auto_20201216_1214'),
    ]

    operations = [
        migrations.RenameField(
            model_name='martialartist',
            old_name='paymentPlan',
            new_name='payment_plan',
        ),
    ]
