# Generated by Django 6.0.1 on 2026-01-26 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0010_auto_20201216_1220'),
        ('styles', '0002_alter_style_id'),
        ('tuition', '0003_alter_paymentplan_id_alter_tuitionpayment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='martialartist',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddIndex(
            model_name='martialartist',
            index=models.Index(fields=['last_name', 'first_name'], name='people_mart_last_na_c1a43c_idx'),
        ),
        migrations.AddIndex(
            model_name='sponsor',
            index=models.Index(fields=['last_name', 'first_name'], name='people_spon_last_na_00f545_idx'),
        ),
    ]
