# Generated by Django 3.1.3 on 2020-12-16 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('frequency', models.IntegerField(choices=[(0, 'None'), (1, 'Monthly'), (2, 'Bi-Monthly'), (3, 'Quarterly'), (6, 'Semi-annual'), (12, 'Annual')], default=1)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
