# Generated by Django 3.1.3 on 2020-11-28 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ranks', '0003_auto_20201128_0414'),
        ('styles', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Styles',
            new_name='Style',
        ),
    ]
